sonar.projectKey=riwaya
sonar.projectName=Riwaya
sonar.projectVersion=1.0

# Chemin des sources à analyser
sonar.sources=src
sonar.exclusions=node_modules/**,.next/**,public/**,**/*.test.*,**/*.spec.*

# TypeScript & JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
