// Villes principales du Maroc (ordre alphabétique)
export const MOROCCO_CITIES = [
    'Agadir',
    'Aïn Harrouda',
    'Al Hoceïma',
    'Azrou',
    'Béni Mellal',
    'Berkane',
    'Berrechid',
    'Casablanca',
    'Chefchaouen',
    'Dakhla',
    'El Jadida',
    'Errachidia',
    'Essaouira',
    'Fès',
    'Guelmim',
    'Ifrane',
    'Kénitra',
    'Khémisset',
    'Khouribga',
    'Ksar El Kébir',
    'Laâyoune',
    'Larache',
    'Marrakech',
    'Meknès',
    'Mohammédia',
    'Nador',
    'Ouarzazate',
    'Oujda',
    'Rabat',
    'Safi',
    'Salé',
    'Settat',
    'Sidi Kacem',
    'Sidi Slimane',
    'Tanger',
    'Tan-Tan',
    'Taourirt',
    'Taroudant',
    'Taza',
    'Témara',
    'Tétouan',
    'Tiznit',
] as const

export type MoroccoCity = typeof MOROCCO_CITIES[number]
